const date=new Date();
 console.log(`1.Todays Date and Time : ${date}`);      
console.log(`2.Day of months : ${date.getDate()}`);
console.log(`3.Day of Weeks : ${date.getDay()}`);
console.log(`4.year : ${date.getFullYear()}`);
console.log(`5.Hours : ${date.getHours()}`);
console.log(`6.Minuttes : ${date.getMinutes()}`);
console.log(`7.Milliseconds : ${date.getMilliseconds()}`);
console.log(`8.Month : ${date.getMonth()}`);
console.log(`9.Date and Day : ${date.toDateString()}`);
console.log(`10.Time : ${date.toTimeString()}`);
var dt=new Date("Aprial 2,2024 23:30:00:");
console.log(`11."Aprial 2,2024 Day " : ${dt}`);
var nandini=new Date("1993-07-02");
console.log(`12.My Birthday : ${nandini}`);
var pravin=new Date("1989-04-28");
console.log(`13.Pravin Birthday : ${pravin}`);
var mayra=new Date("2019-07-25");
console.log(`14.Mayra Birthday : ${mayra}`);
var shambhu=new Date("2021-12-03");
console.log(`15.Shambhu Birthday : ${shambhu}`);